package edu.grinnell.csc207.soundsofsorting.sorts;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.sortevents.CompareEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SortEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.SwapEvent;
import edu.grinnell.csc207.soundsofsorting.sortevents.CopyEvent;


/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */

    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int correctOrderCounter = 0;
        // Loop through the array, swapping adjacent elements until the whole array is sorted
        while (true) {
            for (int i=0; i < arr.length-1 ; i++) {
                if (arr[i].compareTo(arr[i+1]) > 0) {
                    events.add(new CompareEvent<T>(i, i+1));
                    swap(arr, i, i+1);
                    events.add(new SwapEvent<T>(i, i+1));
                } else {
                    correctOrderCounter += 1;
                }
            }
            // If everything is in correct order, break out of the loop
            if (correctOrderCounter == arr.length - 1) {
                break;
            }
            // Reset counter
            correctOrderCounter = 0;
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int sortedSize = 0;
        while(sortedSize < arr.length){
            int minIndex = sortedSize;
            for(int i = sortedSize; i < arr.length; i++){
                if(arr[i].compareTo(arr[minIndex]) < 0){
                    // Add event
                    events.add(new CompareEvent<T>(i, minIndex));
                    minIndex = i;
                }
            }
            swap(arr, sortedSize, minIndex);
            // Add event
            events.add(new SwapEvent<T>(sortedSize, minIndex));
            sortedSize++;
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for(int i = 0; i < arr.length; i++){
            for(int j = 0; j < i; j++){
                if(arr[i].compareTo(arr[j]) <= 0){
                    // Add event
                    events.add(new CompareEvent<T>(i, j));
                    for(int k = i; k > j; k--){ 
                        // swap until the element is in its right place (i.e insertion)
                        swap(arr, k, k-1);
                        // Add event
                        events.add(new SwapEvent<T>(k, k-1));
                    }
                    break;
                }
            }
        }
        return events;
    }

    /**
     * Sorts the given interval of the array specified by startIndex and endIndex according to the mergeSort algorithm
     * @param <T>  the carrier type of the array
     * @param arr the array to sort
     * @param startIndex the first index of the interval being sorted
     * @param endIndex the last index of the interval being sorted
     * @param events the list of sort events being modified
     */
    public static <T extends Comparable<? super T>> void mergeSortHelper(T[] arr, int startIndex, int endIndex, 
                                                                            List<SortEvent<T>> events) {
        if((endIndex - startIndex) > 1){
            // Calculate the length of the subarray, then find the midpoint
            int midIndex = (endIndex - startIndex) / 2 + startIndex;
            T[] result = Arrays.copyOf(arr, arr.length);
            mergeSortHelper(arr, startIndex, midIndex, events);
            mergeSortHelper(arr, midIndex, endIndex, events);

            int i = startIndex;
            int j = midIndex;
            int index = startIndex;
            while(index < endIndex){
                if (i >= midIndex) { // left part done sorting
                    result[index] = arr[j];
                    events.add(new CopyEvent<>(arr[j], index));
                    j++;
                } else if (j >= endIndex) { // right part done sorting
                    result[index] = arr[i];
                    events.add(new CopyEvent<>(arr[i], index));
                    i++;
                } else {
                    if(arr[i].compareTo(arr[j]) <= 0){
                        events.add(new CompareEvent<>(i, j));
                        result[index] = arr[i];
                        events.add(new CopyEvent<>(arr[i], index));
                        i++;
                    }else{
                        result[index] = arr[j];
                        events.add(new CopyEvent<T>(arr[j], index));
                        j++;
                    }
                }
                index++;
            }
            for (int k = startIndex; k < endIndex; k++) {
                arr[k] = result[k];
            }
        }
    }

    /**
     * Sorts the array according to the merge sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        mergeSortHelper(arr, 0, arr.length, events);
        return events;
    }

    /**
     * Sorts the given interval of the array specified by startIndex and endIndex according to the quickSort algorithm
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @param startIndex the first index of the interval being sorted
     * @param endIndex the last index of the interval being sorted
     * @param events the list of sort events being modified
     */
    public static <T extends Comparable<? super T>> void quickSortHelper(T[] arr, int startIndex, int endIndex, 
                                                                        List<SortEvent<T>> events){
        if (endIndex - startIndex > 1) {
            int midIndex = (endIndex - startIndex) / 2 + startIndex;

            //Pick a pivot
            T pivot = arr[midIndex];

            int i = startIndex;
            int j = endIndex - 1;
            
            while (i <= j) {
               while(arr[i].compareTo(pivot) < 0) {
                    i++;
                }
                while(arr[j].compareTo(pivot) > 0) {
                    j--;
                }
                // check if the two pointers passed each other
                if (i <= j) {
                    swap(arr,i,j);
                    events.add(new SwapEvent<T>(i, j));
                    i++;
                    j--;
                }
            }
            quickSortHelper(arr, startIndex, j + 1, events);
            quickSortHelper(arr, i, endIndex, events);
        }
    }

    /**
     * Sorts the array according to the quick sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        quickSortHelper(arr, 0, arr.length, events);
        return events;
    }


    /**
     * Sorts the array according to the gnome sort algorithm.
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> gnomeSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int currentIndex = 1;
        while (currentIndex < arr.length) {
            if (arr[currentIndex-1].compareTo(arr[currentIndex]) > 0) {
                // Add event
                events.add(new CompareEvent<>(currentIndex-1, currentIndex));

                swap(arr, currentIndex-1, currentIndex);
                // Add event
                events.add(new SwapEvent<>(currentIndex-1, currentIndex));

                currentIndex--;
                if (currentIndex == 0) {
                    currentIndex = 1;
                }
            } else {
                currentIndex++;
            }
        }
        return events;
    }

    /**
     * Given an array of Ts and list of SortEvent<T> objects, apply those events to the list in-order.
     * @param <T> the carrier type of the array
     * @param l the array to apply events to
     * @param events the SortEvent list
     */
    public static <T> void eventSort(T[] l, List<SortEvent<T>> events) {
        for (SortEvent<T> event : events) {
            event.apply(l);
        }
    }
}